#pragma once

//Environment models
#define CONTAINER_DIFFUSE "container_diffuse.png"
#define GRASS_DIFFUSE "grass_diffuse.jpg"
#define FAJNA_MUZYCZKA "res/music/Intergalactic Odyssey.ogg"
#define BACKPACK "res/models/backpack/backpack.obj"
#define TANK1 "res/models/tank/tank1.obj"
#define NATURE_TREES3 "res/models/tiles/nature_trees3.obj"
#define CANAL_CORNER_IN "res/models/tiles/canal_corner_in.obj"
#define CANAL_STRAIGHT "res/models/tiles/canal_straight.obj"
#define CANAL_STRAIGHT_W_PIPE "res/models/tiles/canal_straight_w_pipe.obj"
#define CANAL_NOWALL "res/models/tiles/canal_nowall.obj"
#define LAB_PATH_STRAIGHT "res/models/tiles/lab_path_straight.obj"
#define LAB_PATH_CORNER "res/models/tiles/lab_path_corner.obj"
#define LAB_PATH_TJUNCTION "res/models/tiles/lab_path_tjunction.obj"
#define LAB_WALL_STRAIGHT "res/models/tiles/lab_wall_straight.obj"
#define LAB_WALL_CORNER_OUT "res/models/tiles/lab_wall_corner_out.obj"
#define LAB_WALL_CORNER_IN "res/models/tiles/lab_wall_corner_in.obj"
#define LAB_TERMINALS "res/models/tiles/lab_terminals.obj"
#define LAB_TANK1 "res/models/tiles/lab_tank1.obj"
#define LAB_TANK2 "res/models/tiles/lab_tank2.obj"
#define LAB_PLATFORM "res/models/tiles/lab_platform.obj"
#define LAB_PATH_CROSSING "res/models/tiles/lab_path_crossing.obj"
#define LAB_FLOOR_PROPS "res/models/tiles/lab_floor_basic_w_props.obj"
#define LAB_FLOOR_BASIC "res/models/tiles/lab_floor_basic.obj"
#define LAB_CABIN "res/models/tiles/lab_cabin.obj"
#define LAB_GENERATOR "res/models/tiles/lab_generator.obj"
#define NATURE_ROCK "res/models/tiles/nature_rock.obj"
#define NATURE_TREES1 "res/models/tiles/nature_trees1.obj"
#define NATURE_TREES2 "res/models/tiles/nature_trees2.obj"
#define NATURE_TREES3 "res/models/tiles/nature_trees3.obj"
#define NATURE_BRUSH1 "res/models/tiles/nature_brush1.obj"
#define NATURE_BRUSH2 "res/models/tiles/nature_brush2.obj"
#define NATURE_FLOWER "res/models/tiles/nature_flower.obj"
#define NATURE_GROUND1 "res/models/tiles/nature_ground1.obj"
#define NATURE_GROUND2 "res/models/tiles/nature_ground2.obj"
#define NATURE_PATH_STRAIGHT "res/models/tiles/nature_path_straight.obj"
#define NATURE_PATH_TJUNCTION "res/models/tiles/nature_path_tjunction.obj"
#define DIRECTION_SWITCH "res/models/tiles/direction_switch.obj"

//Animated models
#define ANIM "res/models/vampire/dancing_vampire.dae"